### ISSUE TITLE
URL Causes Crash and Can't fill out form

### ISSUE THREAD

**Issue by CodeNeedsCoffee** [EvanTrow/Giftamizer#10]
![image](https://user-images.githubusercontent.com/16927633/141007755-d8840a37-c465-401e-9868-b79e215be30c.png)

URL: https://usstore.edsheeran.com/music-1/vinyl/exclusive-recycled-vinyl.html

**Comment by EvanTrow** [comment]
Prob this 😂

![image](https://user-images.githubusercontent.com/20376151/141702152-d158259a-900d-46b4-857e-1e249ca9d9a4.png)

**Comment by CodeNeedsCoffee** [comment]
needs more non breaking space

**Comment by CodeNeedsCoffee** [comment]
![CowbellGIF](https://user-images.githubusercontent.com/16927633/141871585-3ebfc00c-a504-41c1-a486-bc62f2447896.gif)

**Comment by EvanTrow** [comment]
There site is blocking the requests by the metadata extraction code. 

Added try/catch and a String cast to prevent errors
