### ISSUE TITLE
Autofill email on Android cause issues with authentication

### ISSUE THREAD

**Issue by EvanTrow** [EvanTrow/Giftamizer#8]

**Comment by CodeNeedsCoffee** [comment]
I've noticed on the Android app is doesn't pop up for 1Password to autofill in the email, but allows for the password

**Comment by EvanTrow** [comment]
resolved by adding email type attribute to fields 

https://github.com/EvanTrow/Giftamizer/commit/f7e2f5b809119f9a268f160cf2e78fd107b65341
