### ISSUE TITLE
Random Characters in Auto-filled Description 

### ISSUE THREAD

**Issue by CodeNeedsCoffee** [EvanTrow/Giftamizer#9]
![image](https://user-images.githubusercontent.com/16927633/140752825-a71ce71e-ea1e-444d-a59f-5d71f48824f9.png)

Example URL: https://www.barnesandnoble.com/w/christmas-cheers-straight-no-chaser/18086504?ean=0075678667640

**Comment by EvanTrow** [comment]
![image](https://user-images.githubusercontent.com/20376151/140760897-d7b20759-e1d5-420b-ba42-42499cc3cd6c.png)

looks like its Barnes & Noble's issue 👀

**Comment by CodeNeedsCoffee** [comment]
Interesting, sounds like a them issue 👍
